service: onemorebook-backend

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-dynamodb

custom:
  dotenv:
    path: ./.env
    include:
      - OPENAI_API_KEY
      - AWS_PROFILE
      - AWS_REGION
      - S3_BUCKET
  serverless-dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: false
      migrate: true
      dbPath: "./.dynamodb"
    migration:
      dir: offline/migrations
  conditions:
    offline: ${env:IS_OFFLINE, 'false'}
  s3Bucket: "children-books-imgs"

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'eu-west-1'}
  timeout: 30
  environment:
    DYNAMO_TABLE: ${self:service}-${opt:stage, 'dev'}
    LLM_MODEL: gpt-4o
    IS_OFFLINE: ${self:custom.conditions.offline}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    S3_BUCKET: ${self:custom.s3Bucket}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
          Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMO_TABLE}
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource:
            - arn:aws:s3:::${self:custom.s3Bucket}/*

functions:
  generateBook:
    handler: dist/handlers/generateBook.handler
    timeout: 30
    events:
      - http:
          path: /books
          method: post
          cors: true

  getBook:
    handler: dist/handlers/getBook.handler
    events:
      - http:
          path: /books/{id}
          method: get
          cors: true

  updateStars:
    handler: dist/handlers/updateStars.handler
    events:
      - http:
          path: /books/{id}/stars
          method: put
          cors: true

  listBooks:
    handler: dist/handlers/listBooks.handler
    events:
      - http:
          path: /books
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                sortBy: false
                order: false
                limit: false

resources:
  Resources:
    BooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMO_TABLE}
        AttributeDefinitions:
          - AttributeName: partitionKey
            AttributeType: S
          - AttributeName: id
            AttributeType: S
          - AttributeName: stars
            AttributeType: N
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: partitionKey
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: StarsSortIndex
            KeySchema:
              - AttributeName: partitionKey
                KeyType: HASH
              - AttributeName: stars
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          - IndexName: DateSortIndex
            KeySchema:
              - AttributeName: partitionKey
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
        BillingMode: PAY_PER_REQUEST

    BookCovers:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3Bucket}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: [ '*' ]
              AllowedMethods: [ GET, PUT, POST, DELETE, HEAD ]
              AllowedOrigins: [ '*' ]
              MaxAge: 3000

    BookCoversBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref BookCovers
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action: s3:GetObject
              Resource: arn:aws:s3:::${self:custom.s3Bucket}/*