services:
  - type: web
    name: onemorebook-backend
    env: node
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run start
    rootDir: .
    envVars:
      - key: LLM_MODEL
        value: o3-mini
      # Add your other env vars here
